---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - '*'
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cluster.x-k8s.io
  resources:
  - clusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cluster.x-k8s.io
  resources:
  - clusters/status
  verbs:
  - get
- apiGroups:
  - config.porch.kpt.dev
  resources:
  - repositories
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - infra.nephio.org
  resources:
  - repositories
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infra.nephio.org
  resources:
  - repositories/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - infra.nephio.org
  resources:
  - tokens
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infra.nephio.org
  resources:
  - tokens/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - porch.kpt.dev
  resources:
  - packagerevisions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - porch.kpt.dev
  resources:
  - packagerevisions/status
  verbs:
  - get
